package com.harrrshith.moowe.ui.theme

import androidx.compose.ui.graphics.Color

val md_dark_primary = Color(0xFF3F51B5)
val md_dark_onPrimary = Color(0xFFFFFFFF)
val md_dark_primaryContainer = Color(0xFF1A237E)
val md_dark_onPrimaryContainer = Color(0xFFFFFFFF)
val md_dark_inversePrimary = Color(0xFF9C27B0)
val md_dark_secondary = Color(0xFFD32F2F)
val md_dark_onSecondary = Color(0xFFFFFFFF)
val md_dark_secondaryContainer = Color(0xFFC62828)
val md_dark_onSecondaryContainer = Color(0xFFFFFFFF)
val md_dark_tertiary = Color(0xFF9C27B0)
val md_dark_onTertiary = Color(0xFFFFFFFF)
val md_dark_tertiaryContainer = Color(0xFF6A1B9A)
val md_dark_onTertiaryContainer = Color(0xFFFFFFFF)
val md_dark_error = Color(0xFFD32F2F)
val md_dark_onError = Color(0xFFFFFFFF)
val md_dark_errorContainer = Color(0xFFC62828)
val md_dark_onErrorContainer = Color(0xFFFFFFFF)
val md_dark_background = Color(0xFF1A237E)
val md_dark_onBackground = Color(0xFFFFFFFF)
val md_dark_surface = Color(0xFF4A148C)
val md_dark_onSurface = Color(0xFFEDE7F6)
val md_dark_surfaceVariant = Color(0xFF6A1B9A)
val md_dark_onSurfaceVariant = Color(0xFFD1C4E9)
val md_dark_inverseSurface = Color(0xFF2C1A6A)
val md_dark_inverseOnSurface = Color(0xFFEDE7F6)
val md_dark_outline = Color(0xFFB39DDB)

val md_light_primary = Color(0xFF1E88E5)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFBBDEFB)
val md_light_onPrimaryContainer = Color(0xFF0D47A1)
val md_light_inversePrimary = Color(0xFF3F51B5)
val md_light_secondary = Color(0xFF1976D2)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFF90CAF9)
val md_light_onSecondaryContainer = Color(0xFF0D47A1)
val md_light_tertiary = Color(0xFF7B1FA2)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFE1BEE7)
val md_light_onTertiaryContainer = Color(0xFF4A148C)
val md_light_error = Color(0xFFC62828)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFEF9A9A)
val md_light_onErrorContainer = Color(0xFFB71C1C)
val md_light_background = Color(0xFFE3F2FD)
val md_light_onBackground = Color(0xFF0D47A1)
val md_light_surface = Color(0xFFEDE7F6)
val md_light_onSurface = Color(0xFF4A148C)
val md_light_surfaceVariant = Color(0xFFC5CAE9)
val md_light_onSurfaceVariant = Color(0xFF3F51B5)
val md_light_inverseSurface = Color(0xFF303F9F)
val md_light_inverseOnSurface = Color(0xFFE3F2FD)
val md_light_outline = Color(0xFF9E9E9E)